"""added migrations

Revision ID: 4365a64b8796
Revises: 
Create Date: 2020-02-04 12:40:31.170263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4365a64b8796'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generate',
    sa.Column('user id', sa.INTEGER(), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pin', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user id')
    )
    # ### end Alembic commands ###
